### ISSUE TITLE
Camera Calibration Part 2 Issue Still Not Fixed

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#105]
This was already mentioned in Issue #70, but the second part of the camera calibration procedure still fails using the Python 3 installation (even on the most recent commit to master). The specific part is below...

> Also note that when running the second half of the camera calibration procedure, I get an error originating from line 66 in the solve_for_calibration_params.py script saying 'UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte.' I was able to fix this issue by editing that line to read...

> tt = pickle.load(open(os.path.join(dir_name, "states.pkl"), 'rb'))

> I believe the above issue has to do with the pickle.load function operating slightly different between Python 3 and lower versions. But I know that the above code fixes the issue when working in Python 3.

Note that I also tested this using the Python 2 installation, and it worked just fine there.

Thanks

**Comment by kalyanvasudev** [comment]
This has been fixed in 5b0ed85e3f228e4aab8e8f448b134cf42686f55f on Develop

Will be merged into master by the end of this month.
