### ISSUE TITLE
Manipulation Warning

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#106]
Setup is with Python 3 on an Interbotix Locobot - ROS Kinetic.

When running python ee_pose_control.py, MoveIt fails to plan to both poses, giving a 'Moveit Failed with error code: PLANNING_FAILED' message both times.

When running python ee_pose_pitch_control.py, it executes correctly but outputs the following warning:

![image](https://user-images.githubusercontent.com/52669772/88242965-775b1b00-cc54-11ea-8f06-96b3292bfa3b.png)

Note that I also tested this with the Python 2 Interbotix Installation, and when running the ee_pose_control.py script - MoveIt successfully planned to the first pose but failed planning for the second pose. Also note that the warning mentioned when running the ee_pose_pitch_control.py script does not appear at all in the Python 2 version.

**Comment by kalyanvasudev** [comment]
This warning is a benign datatype warning that has been resolved in the commit - 6ef372940cb9be084fba3bf621a972802ff4d113

And regarding the `ee_pose_control.py` script, I've tested the Develop branch both in python2 and python3. It seems to be working for me without any issues. Please check it again on the Develop branch.

Note that moveit tools have changed significantly on Develop in comparison to the master branch. 

We will merge Develop into master by the end of this month. 

Please re-open the issue if the problem persists.
