### ISSUE TITLE
Python 2 Installation Issue

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#107]
Hi,

When I run ```./locobot_install_all.sh` -t full -p 2 -l interbotix```, I get the following red error message about launchpadlib. It doesn't seem to affect the installation at all, but I thought I'd mention it.

![launchpad_error](https://user-images.githubusercontent.com/52669772/88333444-dfae0900-ccf5-11ea-9623-cd89975ed643.png)

**Comment by kalyanvasudev** [comment]
This seems to be a benign error that seems to be occurring while installing setuptools at this line - 
https://github.com/facebookresearch/pyrobot/blob/master/install_pyrobot.sh#L55

Soon, we are hoping to depreciate python 2.7 in Pyrobot. So, I am going to let this slide for now.
