### ISSUE TITLE
locobot: Source frame elbow_link does not exist

### ISSUE THREAD

**Issue by MithellScott** [facebookresearch/pyrobot#123]
## Steps to reproduce

  1. Set install script to install workspaces into a workspace dir and environments into an env dir
  2. source py3_ws, pyrobot_ws and py3_env: roslaunch locobot_control main.launch use_sim:=true use_base:=true
  3. source py3_ws, pyrobot_ws and py3_env: in python3 terminal from pyrobot import Robot; bot = Robot('locobot')

## Observed Results
tf2.TransformException: canTransform: source elbow link does not exist
## Expected Results
The expected result is that the locobot will initialize and allow control of the gazebo rendering from the console.
This is essentially the navigation exercise from the pyrobot/locobot tutorials.
## Relevant Code
Roslaunch output:
![Roslaunch-output](https://user-images.githubusercontent.com/50934673/93918401-851b3400-fcc9-11ea-974d-b04e3e6675c3.png)

![Pyro-Scripting-Error](https://user-images.githubusercontent.com/50934673/93918090-18a03500-fcc9-11ea-800d-e63e2eab97e0.png)

Install Scripts:
[locobot_install_all.txt](https://github.com/facebookresearch/pyrobot/files/5263113/locobot_install_all.txt)
[install_pyrobot.txt](https://github.com/facebookresearch/pyrobot/files/5263115/install_pyrobot.txt)

```

**Comment by kalyanvasudev** [comment]
hi, could you please elaborate the commands you ran in the 1st terminal?

**Comment by kalyanvasudev** [comment]
>     2\. source py3_ws, pyrobot_ws and py3_env: roslaunch locobot_control main.launch use_sim:=true use_base:=true

Ah I see. You are doing this step wrong. The command should not run inside the virtual environment. 

And for step 3, use the alias created by the install script `load_pyrobot_env` to load the appropriate env.

**Comment by kalyanvasudev** [comment]
Please feel free to re-open the issue if the problem persists.

**Comment by MithellScott** [comment]
I fixed the problem by reinstalling the sim only version. Also when following your instructions above I was not able to fix the issue with the full install(I am running ubuntu 18 and python3).  The error is different, I think from online it has something to do with python file bindings
![pyro3_ws-error](https://user-images.githubusercontent.com/50934673/93967080-a577dc80-fd23-11ea-8274-6e4f8c125783.png)
