### ISSUE TITLE
Does pyrobot support local planer (like dwa or teb)?

### ISSUE THREAD

**Issue by fujin678** [facebookresearch/pyrobot#134]
## Steps to reproduce

  1. _____for navigation,   i noticed pyrobot only uses global planning.   so i wonder if local planning is also supported?
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.

## Expected Results

  * What did you expect to happen?

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by kalyanvasudev** [comment]
Hi, we support movebase planner for locobot. This inturn gives you handles for dwa or teb local planners.
