### ISSUE TITLE
Bouncing effect seen

### ISSUE THREAD

**Issue by yoggieWX** [facebookresearch/pyrobot#152]
Hi,

   We are using a locobot model in our project. We tried using the gripper to grip a brush and to draw a line backwards. We 
  noticed that during the drawing of the line, there was a bounce effect everytime it tried to draw back. When we did a plot of 
   the xyz, we noticed that the Z coordinates seemed to be heading for a huge offset.

  What we did was, we tried using simple commands below and observed still the same effect.
  - set_ee_pose, 
  - move_xyz, 
  - set_ee_pose_pitch_roll.

  I  have attached the plots for both the set_ee_pose and move_xyz for your reference.
  Could you advise us on what could be the possible problem?
  
   Also, could i check on the commands:
   robot.arm.set_ee_pose_pitch_roll(position, pitch=??, roll=0??,plan=True, wait=True)
   Does changing the plan=False and wait=False affect the movements?
  
  ## Observed Results 
   ![set_ee_pose](https://user-images.githubusercontent.com/82563582/114818124-cef67380-9ded-11eb-93ac-eadc9195a5d3.png)
![move_ee_xyz](https://user-images.githubusercontent.com/82563582/114818127-d1f16400-9ded-11eb-83ac-649e41aa93ee.png)

## Expected Results

  * The robot arm is supposed to draw a straight line

**Comment by Jekyll1021** [comment]
plan=True use moveit! planner and controller in the backend. If you have a trajectory that you would like to execute, I highly recommend you look into [move_group_interface.py](https://github.com/facebookresearch/pyrobot/blob/master/src/pyrobot/utils/move_group_interface.py) - directly commanding to waypoints is usually quite bumpy. 

Also, would you mind going through what units the plot are in and how the plot data is gathered?

**Comment by yoggieWX** [comment]
Hi,

Could i find out how do you use the move_group_interface.py. I am using the locobot robot model.

**Comment by Jekyll1021** [comment]
http://docs.ros.org/en/indigo/api/moveit_tutorials/html/doc/pr2_tutorials/planning/scripts/doc/move_group_python_interface_tutorial.html

checkout this tutorial. PyRobot only provide a bridge to moveit!, the API and functionalities are left as-is.
