### ISSUE TITLE
ROS Noetic and Ubuntu 20.04 support

### ISSUE THREAD

**Issue by JiahaoPlus** [facebookresearch/pyrobot#157]
Hi, I was wondering whether support for ROS Noetic and Ubuntu 20.04 is planned?

**Comment by Jekyll1021** [comment]
Core functionalties, including sensors, franka emika arm, and various planner/controller/kinematics/other algorithms: yes, will be supported soon. ETA end of summer.

LoCoBot support: we have plan, but no specific timeline.

**Comment by Mirorrn** [comment]
Any news regarding a newer Version?
