### ISSUE TITLE
Cannot import PyKDL

### ISSUE THREAD

**Issue by hzyjerry** [facebookresearch/pyrobot#18]
Hi, I am using pyrobot on Ubuntu 16.04.

After successful installation, I executed `python base_position_control.py` and got the following error:

```
Traceback (most recent call last):
  File "base_position_control.py", line 12, in <module>
    from pyrobot import Robot
  File "/home/jerrhe/miniconda3/envs/ros/lib/python2.7/site-packages/pyrobot/__init__.py", line 6, in <module>
    from pyrobot.core import Robot
  File "/home/jerrhe/miniconda3/envs/ros/lib/python2.7/site-packages/pyrobot/core.py", line 16, in <module>
    import PyKDL as kdl
ImportError: No module named sip
```

I also tried `sudo apt-get install python-sip` but doesn't seem to help. Have you any suggestion for the issue? Thanks!

**Comment by kalyanvasudev** [comment]
Try removing SIP and installing it using "pip install sip"

**Comment by kalyanvasudev** [comment]
Also, PyRobot python api is configured to work with the virtual environment setup we provided and Python2.7  

Looks like you are using a different environment?

**Comment by kalyanvasudev** [comment]
I assume you were to able the resolve the issue.. Closing this issue for now.
