### ISSUE TITLE
Installation issue with pip

### ISSUE THREAD

**Issue by ozbeluga** [facebookresearch/pyrobot#23]
After following the steps you shared for installation I am having trouble running locobot_install_all.sh. I get the following:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

I searched online, but only got confused more about the issue. Do you have any idea about this?

Thank you!

**Comment by kalyanvasudev** [comment]
Hi,

Could you please provide more information about your setup, etc?

Also, could you post the entire error you saw?

**Comment by Siddu733** [comment]
I have not got any issues while installing pyrobot. I have done using "pip install pyrobot" command in python terminal. For any issues, visit https://pypi.org/project/pyrobot/ .

**Comment by kalyanvasudev** [comment]
Hi @Siddu733 , the pyrobot you mentioned in the link is a different project. It is not associated with this project or this repository.

**Comment by kalyanvasudev** [comment]
Closing this issue as it is unrelated.
