### ISSUE TITLE
Why I have the kinect but have error

### ISSUE THREAD

**Issue by Ljh0121** [facebookresearch/pyrobot#25]
My kinect works fine.

[ERROR] [1566562676.166651880]: No RealSense devices were found! Terminating RealSense Node...
[FATAL] [1566562676.371803560]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera_manager-1] process has died [pid 2894, exit code 1, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/ethan/.ros/log/d7eb47f0-c59e-11e9-bf66-6045cb6a2f1f/camera-realsense2_camera_manager-1.log].
log file: /home/ethan/.ros/log/d7eb47f0-c59e-11e9-bf66-6045cb6a2f1f/camera-realsense2_camera_manager-1*.log
[camera/realsense2_camera-2] process has died [pid 2895, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/ethan/.ros/log/d7eb47f0-c59e-11e9-bf66-6045cb6a2f1f/camera-realsense2_camera-2.log].
log file: /home/ethan/.ros/log/d7eb47f0-c59e-11e9-bf66-6045cb6a2f1f/camera-realsense2_camera-2*.lo

**Comment by kalyanvasudev** [comment]
I assume my earlier response answers your question? Closing this issue for now.
