### ISSUE TITLE
Error while running Camera Calibration

### ISSUE THREAD

**Issue by vikashranjan** [facebookresearch/pyrobot#26]
I have built a LoCoBot without the robotic arm and movable camera. I get the following issue while I run Camera Calibration.LoCoBot installation is done using locobot_install_all.sh .

Command : roslaunch locobot_calibration calibrate.launch base:=kobuki
Hardware : 
- Intel NUC i5 with 8 Gb Ram
- Intel D435 camera
- Base Kobuki base

Error:

(pyenv_pyrobot) vikash@vikash-desktop:~$ roslaunch locobot_calibration calibrate.launch base:=kobuki
... logging to /home/vikash/.ros/log/07f81912-ca6a-11e9-8875-00c2c6bcf3fe/roslaunch-vikash-desktop-27552.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://vikash-desktop:45445/

SUMMARY

PARAMETERS
 * /ar_track_alvar/marker_size: 3.0
 * /ar_track_alvar/max_new_marker_error: 0.08
 * /ar_track_alvar/max_track_error: 0.2
 * /ar_track_alvar/output_frame: camera_link
 * /base: kobuki
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_imu: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_fps: 30
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_height: 480
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra1_width: 640
 * /camera/realsense2_camera/infra2_fps: 30
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_height: 480
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra2_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/unite_imu_method: none
 * /dynamixel_info: /home/vikash/low_...
 * /locobot_controller/dxl_read_period: 0.01
 * /locobot_controller/dxl_write_period: 0.01
 * /locobot_controller/publish_period: 0.01
 * /move_group/allow_trajectory_execution: True
 * /move_group/arm/default_planner_config: ESTkConfigDefault
 * /move_group/arm/longest_valid_segment_fraction: 0.005
 * /move_group/arm/planner_configs: ['SBLkConfigDefau...
 * /move_group/arm/projection_evaluator: joints(joint_1,jo...
 * /move_group/capabilities: 
 * /move_group/controller_list: [{'default': True...
 * /move_group/disable_capabilities: 
 * /move_group/gripper/default_planner_config: ESTkConfigDefault
 * /move_group/gripper/longest_valid_segment_fraction: 0.005
 * /move_group/gripper/planner_configs: ['SBLkConfigDefau...
 * /move_group/gripper/projection_evaluator: joints(joint_6,jo...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/BFMTkConfigDefault/balanced: 0
 * /move_group/planner_configs/BFMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/BFMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/BFMTkConfigDefault/heuristics: 1
 * /move_group/planner_configs/BFMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/BFMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/BFMTkConfigDefault/optimality: 1
 * /move_group/planner_configs/BFMTkConfigDefault/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMTkConfigDefault/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/BiESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiESTkConfigDefault/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRTkConfigDefault/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/init_temperature: 100
 * /move_group/planner_configs/BiTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/type: geometric::BiTRRT
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/FMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/FMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/FMTkConfigDefault/heuristics: 0
 * /move_group/planner_configs/FMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/FMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/FMTkConfigDefault/radius_multiplier: 1.1
 * /move_group/planner_configs/FMTkConfigDefault/type: geometric::FMT
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRTkConfigDefault/epsilon: 0.4
 * /move_group/planner_configs/LBTRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBTRRTkConfigDefault/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRMkConfigDefault/range: 0.0
 * /move_group/planner_configs/LazyPRMkConfigDefault/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstarkConfigDefault/type: geometric::LazyPR...
 * /move_group/planner_configs/PDSTkConfigDefault/type: geometric::PDST
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/ProjESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ProjESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ProjESTkConfigDefault/type: geometric::ProjEST
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/SPARSkConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARSkConfigDefault/max_failures: 1000
 * /move_group/planner_configs/SPARSkConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARSkConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARSkConfigDefault/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwokConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwokConfigDefault/max_failures: 5000
 * /move_group/planner_configs/SPARStwokConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwokConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwokConfigDefault/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDEkConfigDefault/degree: 16
 * /move_group/planner_configs/STRIDEkConfigDefault/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/STRIDEkConfigDefault/max_degree: 18
 * /move_group/planner_configs/STRIDEkConfigDefault/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDEkConfigDefault/min_degree: 12
 * /move_group/planner_configs/STRIDEkConfigDefault/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDEkConfigDefault/range: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDEkConfigDefault/use_projected_distance: 0
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/sensors: [{'point_subsampl...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/allowed_start_tolerance: 0.0
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/arm/kinematics_solver: trac_ik_kinematic...
 * /robot_description_kinematics/arm/kinematics_solver_attempts: 3
 * /robot_description_kinematics/arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/arm/kinematics_solver_timeout: 0.005
 * /robot_description_planning/joint_limits/joint_1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_1/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_1/max_velocity: 1
 * /robot_description_planning/joint_limits/joint_2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_2/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_2/max_velocity: 1
 * /robot_description_planning/joint_limits/joint_3/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_3/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_3/max_velocity: 1
 * /robot_description_planning/joint_limits/joint_4/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_4/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_4/max_velocity: 1
 * /robot_description_planning/joint_limits/joint_5/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_5/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_5/max_velocity: 1
 * /robot_description_planning/joint_limits/joint_6/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_6/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_6/max_velocity: 1
 * /robot_description_planning/joint_limits/joint_7/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_7/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_7/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_7/max_velocity: 1
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rviz_vikash_desktop_27552_5079649717650137372/arm/kinematics_solver: trac_ik_kinematic...
 * /rviz_vikash_desktop_27552_5079649717650137372/arm/kinematics_solver_attempts: 3
 * /rviz_vikash_desktop_27552_5079649717650137372/arm/kinematics_solver_search_resolution: 0.005
 * /rviz_vikash_desktop_27552_5079649717650137372/arm/kinematics_solver_timeout: 0.005
 * /teleop: False
 * /torque_control: False
 * /use_arm: True
 * /use_base: False
 * /use_camera: True
 * /use_sim: False
 * /use_vslam: False

NODES
  /camera/
    color_rectify_color (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /
    ar_track_alvar (ar_track_alvar/individualMarkersNoKinect)
    calibration_tf_broadcaster (locobot_calibration/calibration_publish_transforms.py)
    locobot_controller (locobot_control/locobot_controller)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_vikash_desktop_27552_5079649717650137372 (rviz/rviz)

auto-starting new master
process[master]: started with pid [27562]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 07f81912-ca6a-11e9-8875-00c2c6bcf3fe
process[rosout-1]: started with pid [27575]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [27592]
process[camera/realsense2_camera-3]: started with pid [27593]
process[camera/color_rectify_color-4]: started with pid [27594]
process[camera/points_xyzrgb_hw_registered-5]: started with pid [27602]
process[locobot_controller-6]: started with pid [27608]
process[calibration_tf_broadcaster-7]: started with pid [27624]
process[robot_state_publisher-8]: started with pid [27635]
[PortHandlerLinux::SetupPort] Error opening serial port!
[ERROR] [1567089237.319877760]: [DynamixelDriver] Failed to open the port!
[ERROR] [1567089237.319951456]: Please check USB port name
process[move_group-9]: started with pid [27643]
process[rviz_vikash_desktop_27552_5079649717650137372-10]: started with pid [27662]
process[ar_track_alvar-11]: started with pid [27670]

[ INFO] [1567089237.446671320]: Initializing nodelet with 4 worker threads.
[ INFO] [1567089237.458089386]: Loading robot model 'locobot'...
[ INFO] [1567089237.458204474]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1567089237.548355008]: Subscribing to info topic

REQUIRED process [locobot_controller-6] has died!
process has died [pid 27608, exit code -11, cmd /home/vikash/low_cost_ws/devel/lib/locobot_control/locobot_controller /dev/ttyUSB_dyna 1000000 __name:=locobot_controller __log:=/home/vikash/.ros/log/07f81912-ca6a-11e9-8875-00c2c6bcf3fe/locobot_controller-6.log].
log file: /home/vikash/.ros/log/07f81912-ca6a-11e9-8875-00c2c6bcf3fe/locobot_controller-6*.log
Initiating shutdown!

[ INFO] [1567089237.615415964]: rviz version 1.12.17
[ INFO] [1567089237.615529828]: compiled against Qt version 5.5.1
[ INFO] [1567089237.615580997]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1567089237.650988379]: AR tracker reconfigured: ENABLED 8.00 3.00 0.08 0.20
[ar_track_alvar-11] killing on exit
[rviz_vikash_desktop_27552_5079649717650137372-10] killing on exit
[move_group-9] killing on exit
[robot_state_publisher-8] killing on exit
[calibration_tf_broadcaster-7] killing on exit
Traceback (most recent call last):
  File "/home/vikash/low_cost_ws/src/pyrobot/robots/LoCoBot/locobot_calibration/nodes/calibration_publish_transforms.py", line 16, in <module>
    import tf
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 39, in <module>
    from .buffer_interface import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/buffer_interface.py", line 32, in <module>
    import roslib; roslib.load_manifest('tf2_ros')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 167, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 211, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 201, in get_path
    self._update_location_cache()
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 184, in _update_location_cache
    list_by_path(self._manifest_name, path, cache)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 61, in list_by_path
    for d, dirs, files in os.walk(path, topdown=True, followlinks=True):
  File "/home/vikash/pyenv_pyrobot/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/vikash/pyenv_pyrobot/lib/python2.7/os.py", line 286, in walk
[locobot_controller-6] killing on exit
    if isdir(join(top, name)):
  File "/home/vikash/pyenv_pyrobot/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
KeyboardInterrupt
[camera/points_xyzrgb_hw_registered-5] killing on exit
[camera/realsense2_camera-3] killing on exit
[camera/color_rectify_color-4] killing on exit
[camera/realsense2_camera_manager-2] killing on exit
libGL error: failed to create drawable
individualMarkersNoKinect: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
Starting context monitors...
Context monitors started.
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...

You can start planning now!

[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by kalyanvasudev** [comment]
The camera calibration script is design to do hand-eye calibration for the robot arm i.e, to find the transformation between the camera and the arm end-effector. This is different from camera intrinsics calibration. 

Since you do not have the arm mounted on your LoCoBot, this calibration wont work and is not needed.

**Comment by vikashranjan** [comment]
Thanks for your reply. I assumed it's camera intrinsics calibration.
