### ISSUE TITLE
Unknown attribute: name

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#29]
## Steps to reproduce

  1. Launch the main.launch file making sure that the use_arm argument is set to true
  2. run any example python script that creates an instance of 'Robot'

## Observed Results

Besides for the normal terminal output (in the terminal that the script is run) dictating what joints moveit is using, there is a info message saying... 'Unknown attribute: name'

## Expected Results

The 'Unknown attribute: name' message should not appear.

## Relevant Code

Not sure what could cause this issue. I did note that there were other similar info messages about 'Unknown tag: hardwareInterface'. This was easily fixed by deleting all the hardwareInterface tags under the actuator tags in the locobot_description.urdf. As explained [here](http://wiki.ros.org/urdf/XML/Transmission) and [here](https://github.com/ros/urdf_parser_py/issues/6), this tag is not needed for ROS versions higher than and including Indigo. I thought that perhaps the 'Unknown attribute: name' message might also be related to the URDF but still can't figure it out. From the fact that this message seems to only appear if the 'use_arm' argument in the main.launch file is set to True, it seems to be related to the 'arm' code in core.py.

This problem was found using ROS Kinetic on Ubuntu 16.04 with the Intel NUC7i5BNH

**Comment by kalyanvasudev** [comment]
Seems like this warning is no longer appearing? I am closing this issue for now. But please feel free to open it again if the warning re-appears.
