### ISSUE TITLE
robot name parsing from config file is incomplete 

### ISSUE THREAD

**Issue by harryrobotics** [facebookresearch/pyrobot#3]
I created config file name : kobuki_config or husky_config for kobuki and husky robot.
When I run : 

robot = Robot(‘kobuki’) or 
robot = Robot(‘husky’)

Program will throw an error that : it can’t find the robot name husk or kobuk 
The letter i and y are not capture when parsing the file name robot_config.py .

I ended up naming the file and robot is husk instead of husky.

**Comment by kalyanvasudev** [comment]
Thank you for bringing this to our attention. The bug has been resolved in the commit a27649d6751c8e15111d3e391725419af41ccd16

Please let us know if have any more questions or doubts on how to add a new robot to PyRobot.
We are excited to see more robots on this platform :)

**Comment by sushil-bharati** [comment]
nice catch, @kalyanvasudev
