### ISSUE TITLE
Wrong Dynamixel Motor Power Hub Link on Locobot Page

### ISSUE THREAD

**Issue by msr-peng** [facebookresearch/pyrobot#30]
Motor power hub's link on [Locobot components page](https://locobot-website.netlify.com/docs/k_step_2) leads to the wrong product.
![power_hub](https://user-images.githubusercontent.com/32179387/65375922-ed22de80-dc5f-11e9-90b8-c2fe060d6bfa.png)
     
It leads to the [following power hub](https://www.trossenrobotics.com/6-port-ax-mx-power-hub):
![wrong_power_hub](https://user-images.githubusercontent.com/32179387/65375972-60c4eb80-dc60-11e9-9370-4e7ae361f402.png)
     
However, **the right power hub's port is slightly different**. [Here](https://www.trossenrobotics.com/3-pin-x-series-power-hub.aspx) is the right one:
![right_power_hub](https://user-images.githubusercontent.com/32179387/65376015-d335cb80-dc60-11e9-9a73-4ac2bb4c5b43.png)
     
For those who don't buy the arm which come with the motor power hub, it's very easy to buy the wrong one given the instruction on locobot page. So please update the correct link.

**Comment by Dhiraj100892** [comment]
Hi @msr-peng ,

Thanks for pointing it out and I am sorry for the mistake. I have updated it on the website.

**Comment by msr-peng** [comment]
> Hi @msr-peng ,
> 
> Thanks for pointing it out and I am sorry for the mistake. I have updated it on the website.

Cool~ Then I'll close this issue.
