### ISSUE TITLE
Missing caster_back_link Gazebo tag

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#45]
I'm not seeing simulation parameters for the 'caster_back_link' in the 'locobot_description.urdf' file over [here](https://github.com/facebookresearch/pyrobot/blob/master/robots/LoCoBot/locobot_description/urdf/locobot_description.urdf) (scroll to line number 787). I assume this could be fixed by just copying the gazebo tag for 'caster_front_link' and using it for 'caster_back_link'

**Comment by kalyanvasudev** [comment]
This issue has been resolved in [this](https://github.com/facebookresearch/pyrobot/commit/7e2a417c68d3ffe801e5dda8bb490457fa31c518#diff-abba83f2085fe1938ca230d0f13bea1a) commit.
