### ISSUE TITLE
how to navigate and take pictures simultaneously

### ISSUE THREAD

**Issue by yimengli46** [facebookresearch/pyrobot#59]
When I was trying the example code `base_trajectory_tracking.py`,
I was wondering if I can let the locobot take pictures during navigation. 
Is there an API to use to do this? Or I have to modify `execute_plan()` in the `base_control_utils.py` directly?

**Comment by kalyanvasudev** [comment]
Hi, we have a non-blocking version in development that would let LoCoBot collect pictures while navigating. It will be open-sourced soon.
