### ISSUE TITLE
Is Ubuntu 18.04 supported?

### ISSUE THREAD

**Issue by Heavy02011** [facebookresearch/pyrobot#6]

**Comment by kalyanvasudev** [comment]
Ubuntu 16.04 is the only version supported at the moment as many robots only work with this Ubuntu version.

**Comment by kalyanvasudev** [comment]
We have ubuntu 18.04 support now in a different feature branch

**Comment by abhishek-tcs-rni** [comment]
@kalyanvasudev Could you please mention which branch has support for Ubuntu 18.04 ?

**Comment by Jekyll1021** [comment]
> @kalyanvasudev Could you please mention which branch has support for Ubuntu 18.04 ?

Now we have ubuntu 18.04 support for `master` and `Develop`.
