### ISSUE TITLE
[Feature Contribution] Tests for a custom robot

### ISSUE THREAD

**Issue by mbusy** [facebookresearch/pyrobot#61]
Hi, I started to integrate a custom robot (Pepper robot) in PyRobot a while ago, and I ultimately wish to submit this work through a PR.

Most of the integration is already done, but I do have a question regarding the tests. Would it be better to modify the existing test files (filtering which tests should be launched according to the __botname__ parameter), or to simply to add new test files for the Pepper robot ?

**Comment by kalyanvasudev** [comment]
Hi, Please create a separate set of tests for the Pepper robot by making a folder inside the "tests" folder.

**Comment by mbusy** [comment]
Hi @kalyanvasudev, thanks for the precision!

**Comment by kalyanvasudev** [comment]
I hope this answers your question. Closing this issue for now. Please feel free to re-open it if you have any further questions.

**Comment by mbusy** [comment]
It does thanks, I will submit a PR as soon as I get an answer from my company regarding the CLA.
