### ISSUE TITLE
Python 3 Installation Issues

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#62]
During the installation of Pyrobot (with Python 3), the locobot_install_all.sh script executes this command `pip3 install --ignore-installed -r requirements_python3.txt`.

While it's installing packages, an error message displays saying that the required Numpy version for 'bezier' is at least 1.18.1. However, the [requirements_python3.txt](https://github.com/facebookresearch/pyrobot/blob/master/robots/LoCoBot/requirements_python3.txt) file specifies that it must be equal to 1.17.0. I manually changed this to be 1.18.1 and the problem went away. I believe this occurred since the newest bezier package was released February 20th of this year.

On a different note, when trying to run the camera calibration script (in one terminal I type `roslaunch locobot_calibration calibrate.launch base:=kobuki` and in the second I type `python scripts/collect_calibration_data.py \
    --data_dir tmp/calibration-data/v1/ \
    --botname locobot`
after activating the virtual environment (`load_pyrobot_env`)). However, I get an error message of...

`Traceback (most recent call last):
  File "scripts/collect_calibration_data.py", line 18, in <module>
    import cv2
ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type`.

This confuses me... if the python 3 environment was activated, why is python looking at python2 packages?!?!?!?

Could you help me fix this issue? I'm in the middle of creating a new SSD image with the most up-to-date PyRobot repo and Python3 (as Python2 is no longer supported) to go with the locobot platforms that we are distributing.

Thanks!

Note that if you do the following, the error goes away....
```
import sys

sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages') # in order to import cv2 under python3

import cv2

sys.path.append('/opt/ros/kinetic/lib/python2.7/dist-packages') # append back in order to import rospy
```

but this is very hacky...

...and then you get an error later on when the script tries to import tf...

```
Traceback (most recent call last):
  File "scripts/collect_calibration_data.py", line 22, in <module>
    import tf
  File "/home/locobot/pyrobot_catkin_ws/devel/lib/python2.7/dist-packages/tf/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 30, in <module>
  File "/home/locobot/pyrobot_catkin_ws/devel/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 38, in <module>
  File "/home/locobot/pyrobot_catkin_ws/devel/lib/python2.7/dist-packages/tf2_py/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 38, in <module>
ImportError: dynamic module does not define module export function (PyInit__tf2)
```

I noticed that you're using Python3.6, but over [here](https://github.com/facebookresearch/pyrobot/blob/master/install_pyrobot.sh#L99), it looks like you might be building for Python3.5?

**Comment by kalyanvasudev** [comment]
Hi, all of these issues have now been resolved on the Develop branch. Soon I will merge them onto Master after some testing. Thanks for bringing this to my attension.

Regarding the the `cv2` import in python3, with ROS installed, there is no other way to do it than the one you mentioned. I made it look clean using this function - https://github.com/facebookresearch/pyrobot/blob/Develop/src/pyrobot/utils/util.py#L17

So, if you want to perform  `import cv2` in python3 with ROS installed, please use the follow snippet,
```
from pyrobot.utils.util import try_cv2_import
cv2 = try_cv2_import()
```

**Comment by swinterbotix** [comment]
Sounds great! Looking forward to trying this out soon once you merge to master.

**Comment by swinterbotix** [comment]
Any idea on when the issue that's causing the 'checks to fail' will be resolved?

**Comment by kalyanvasudev** [comment]
Hi The checks that are failing are benign controller errors in Gazebo. 
Also, now the master is updated to reflect changes from Develop. So, all the python3 install issues and CV2 errors are resolved.

Please let me know if you have any further questions. Closing this issue for now.

**Comment by swinterbotix** [comment]
Amazing! Thanks so much. I'll try doing a clean install with the Python3 Version soon and let you know if any other issues come up.
