### ISSUE TITLE
Python3 Runtime Issues/Warnings

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#71]
Platform is Ubuntu 16.04.6 ROS Kinetic using latest pyrobot code.

In one terminal, I launch...

`roslaunch locobot_control main.launch use_base:=true use_arm:=true use_camera:=true`

In a second terminal, I navigate to the manipulation directory for the locobot, and type (after sourcing the workspace)

`python ee_pose_control.py` or any other script.

Every time, I get a couple of warnings saying...

![image](https://user-images.githubusercontent.com/52669772/79702437-74721800-826a-11ea-9a11-9001676d4dca.png)

MoveIt also fails more often than not to plan. I believe this can be remedied by changing the default planner to RRTConnectkConfigDefault [here](https://github.com/facebookresearch/pyrobot/blob/master/robots/LoCoBot/locobot_moveit_config/config/ompl_planning.yaml#L124).

**Comment by kalyanvasudev** [comment]
I've resolved the warnings on the Develop branch. Will push the changes to master after confirming.

On the other hand, moveit issue a rather interesting one. Let me investigate it more.

**Comment by kalyanvasudev** [comment]
Looks like all the warnings are resolved now. I've also updates the moveit default planner to RRTConnectkConfigDefault. 

Closing this issue. Please re-open it if the issue persists.
