### ISSUE TITLE
Locobase vs. Locobot

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#72]
There are quite a few times in the pyrobot repo where 'locobase' is used instead of 'locobot'. I'm not sure why this is the case considering that 'locobase' is not even a valid botname...

To find them, navigate to low_cost_ws/src and type...

`grep -rn "locobase" pyroboot/`

Could this be updated please to avoid confusion?

Thanks

**Comment by kalyanvasudev** [comment]
Hi, thank for bringing it to my attention. This issue has been addressed in [this](https://github.com/facebookresearch/pyrobot/commit/a0f95f94076eb1d06b7a3961916bd962dc87604b) commit.
