### ISSUE TITLE
PyRobot Installation Scripts Doesn't Work for Ubuntu 18.04 and Python 3

### ISSUE THREAD

**Issue by msr-peng** [facebookresearch/pyrobot#83]
Hey Kalyan, I'm not sure whether PyRobot can also run on Ubuntu 18.04 by Python 3. But I did run issues with installation when execute [locobot_install_all.sh](https://github.com/facebookresearch/pyrobot/blob/master/robots/LoCoBot/install/locobot_install_all.sh) on a fresh Ubuntu 18.04.

To make the installation scripts run without errors, I did 4 minor modifications:

  1. I added `sudo apt-get install python-rosdep` before [Line 134](https://github.com/facebookresearch/pyrobot/blob/master/robots/LoCoBot/install/locobot_install_all.sh#L134), otherwise, there would be `sudo: rosdep: command not found` error.
  2. I deleted `python-software-properties` in [`install_pyrobot.sh` Line 67](https://github.com/facebookresearch/pyrobot/blob/master/install_pyrobot.sh#L67), since `python-software-properties` package is only available for Ubuntu 12-, and `software-properties-common` is its alternative.
  3. I commented out [`install_pyrobot.sh` Line 68](https://github.com/facebookresearch/pyrobot/blob/master/install_pyrobot.sh#L68), otherwise, there would be errors like this:

![error_0](https://user-images.githubusercontent.com/32179387/82268991-f1f67a00-9935-11ea-9958-8334c43eee43.png)

  4. For [`install_pyrobot.sh` Line 107](https://github.com/facebookresearch/pyrobot/blob/master/install_pyrobot.sh#L107), instead of using `catkin_make`, I used `catkin_make_isolated`, otherwise would occur errors like this:
![error_1](https://user-images.githubusercontent.com/32179387/82269612-cd9b9d00-9937-11ea-9685-3ae957cff610.png)

## Observed Results
After installation, when import pyrobot module in PyRobot virtual env this ImportError would occur:
![error_2](https://user-images.githubusercontent.com/32179387/82269736-25d29f00-9938-11ea-9707-40dcac085ec2.png)
 
It has something do do with [`client.py` Line 68](https://github.com/kalyanvasudev/ros_comm/blob/melodic-devel/clients/rospy/src/rospy/client.py#L68) and [roscpp.srv](https://github.com/kalyanvasudev/ros_comm/tree/melodic-devel/clients/roscpp/srv) module. I noticed there isn't `GetLoggersResponse`, `SetLoggerLevelResponse` module. So is the installation scripts for Ubuntu 18.04 and Python 3 still unfinished?

**Comment by kalyanvasudev** [comment]
Hi @msr-peng, Thanks for bringing this to my attention. Yeah,  I've observed these issues a week back and had resolved them on the Develop branch. 

I will also soon merge the changes from Develop branch onto master in a day.

**Comment by msr-peng** [comment]
Oh that's cool. I'll close this issue then.
