### ISSUE TITLE
How to run grasping demo in gazebo

### ISSUE THREAD

**Issue by wangjiwang** [facebookresearch/pyrobot#84]
Excuse me, I do not have any robot now. I want to run the grasping demo in gazebo. How could I do it?

**Comment by kalyanvasudev** [comment]
Please checkout our tutorials on the - https://www.pyrobot.org/

**Comment by wangjiwang** [comment]
> Please checkout our tutorials on the - https://www.pyrobot.org/

@kalyanvasudev Yes, I have checked the tutorials on the https://www.pyrobot.org/. I am sorry because I did not find the tutorials I need. Could you please tell me more details?

**Comment by kalyanvasudev** [comment]
Tutorials are mentioned in this page - https://www.pyrobot.org/docs/overview

Please feel free to open this issue again if you have further questions.
