### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by swinterbotix** [facebookresearch/pyrobot#89]
Hi,

I just installed the latest code on my locobot, and while the installation script worked flawlessly (full install, Python 3, interbotix locobot, ros kinetic on Ubuntu 16.04, Intel NUC7i5BNH), I ran into an issue right afterwards.

Specifically, I opened a terminal and typed `roslaunch locobot_control main.launch use_arm:=true use_base:=true use_camera:=true`, and got the following error...

![image](https://user-images.githubusercontent.com/52669772/84335253-1111b180-ab5a-11ea-9b0f-22cd8bc86ee3.png)

I noticed (from your commits) that it looked like you were going to include some sort of gpmp action server but it didn't make the final cut. However, it looks like some part of it made it through to the latest commit. Any way that you could take a look at this?

Also, I just tried to run the ee_pose_control.py script. Unfortunately, while moveit is able to plan and move the arm successfully to the first goal pose, it consistently fails to move the arm to the second pose. The error message is:

Moveit Failed with error code: PLANNING_FAILED

**Comment by kalyanvasudev** [comment]
1. I've resolved the runtime error in the latest commit on the master. 

2. Let me look into the ee_pose_control.py script.

**Comment by swinterbotix** [comment]
Sounds good! Let me know know what you find

**Comment by kalyanvasudev** [comment]
HI @swinterbotix , I've fixed the moveit issue on the Develop branch. Now, planning is more reliable than earlier. I will merger into the master in about 10 days.

**Comment by swinterbotix** [comment]
Amazing! Looking forward to that.

**Comment by swinterbotix** [comment]
Any update?
