### ISSUE TITLE
example grasping:   arm does not go down low enough

### ISSUE THREAD

**Issue by fujin678** [facebookresearch/pyrobot#91]
## Steps to reproduce

  1. _____py 2.7
  2. _____locobot
  3. _____

## Observed Results

When running sample grasping,  camera can location object.  Arm also moves above object (roughly, looks OK).  But arm does not go down low enough (I mean, go low to properly touch floor) to pick up object.   Does it mean my camera /arm has some calibration error?

## Expected Results

  * What did you expect to happen?

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by kalyanvasudev** [comment]
Yeah, this seems like a arm-camera calibration issue. Please consider re-calibrating the robot-camera again.
