### ISSUE TITLE
https://pyrobot.org/docs/network not opening

### ISSUE THREAD

**Issue by priyashkla** [facebookresearch/pyrobot#95]
## Steps to reproduce

https://pyrobot.org/docs/network

## Observed Results

  * What happened?  This could be a description, log output, etc.
![image](https://user-images.githubusercontent.com/33479052/86352300-368a6a80-bc83-11ea-9d82-6e94dfb95736.png)

```

**Comment by kalyanvasudev** [comment]
I'm working on the certificates. For now, you can click on the 'Advanced' icon and proceed to the website without ssl certificates.
